config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]

      resources :nodes, only: [:index, :update]
    end
  end

  resources :registrations

  resources :nodes

  resources :hubs

  get 'sessions/new'

  resources :users

  resources :payments

  resources :parkings
  get 'enter', to: 'parkings#enter'
  get 'exit', to: 'parkings#exit'

  resources :cars

  resources :lots
  get 'devices', to: 'lots#devices'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root :to => 'nodes#index', :as => 'allnodes'

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :registrations  # must be two
  has_many :hubs, :through => :registrations
end

app/controllers/api/v1/nodes_controller.rb
class Api::V1::NodesController < Api::V1::BaseController
  # before_action :authenticate_user!, only: [:update]
  def index
  end

  def update
    @node = Node.find(params[:id])

    @node.update_attributes(update_params)

    @node = Node.find(params[:id])
    Rails.logger.info("---------------------#{@node.inspect}")
  end

  private

  def update_params
    params.require(:node).permit(:status)
  end

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:hardware_id, :status, :main_hub, :alt_hub, :monitor, :display)
    end
end

app/helpers/api/v1/nodes_helper.rb
module Api::V1::NodesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hardware_id %><br>
    <%= f.text_field :hardware_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :main_hub %><br>
    <%= f.number_field :main_hub %>
  </div>
  <div class="field">
    <%= f.label :alt_hub %><br>
    <%= f.number_field :alt_hub %>
  </div>
  <div class="field">
    <%= f.label :monitor %><br>
    <%= f.number_field :monitor %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.number_field :display %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h2>停车位状态</h2>
<h5>红色，已停；绿色：空车位；黄色：故障；灰色：待定</h5>

<% i =0 %>
<table class="table table-striped">
  <tbody>
    <% @nodes.each do |node| %>
      <% if i%16 == 0 %>
        <tr>
      <% end %>
        <td>

          <% if node.status == 'busy' %>
            <%= button_to("node", node_path(node.id), :class => "btn btn-danger btn-circle", method: :get) %>
          <% elsif node.status == 'idle' %>
          <%= button_to("node", node_path(node.id), :class => "btn btn-success btn-circle", method: :get) %>
          <% else %>
          <%= button_to("node", node_path(node.id), :class => "btn btn-default btn-circle", method: :get) %>
          <% end %>

          <span class="label label-default"> <%= node.hardware_id %></span>

        </td>
      <% if i%16 == 15 or i == @nodes.length - 1 %>
        </tr>
      <% end %>

      <% i = i+1 %>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hardware:</strong>
  <%= @node.hardware_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @node.status %>
</p>

<p>
  <strong>Main hub:</strong>
  <%= @node.main_hub %>
</p>

<p>
  <strong>Alt hub:</strong>
  <%= @node.alt_hub %>
</p>

<p>
  <strong>Monitor:</strong>
  <%= @node.monitor %>
</p>

<p>
  <strong>Display:</strong>
  <%= @node.display %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

<h3> Registrations </h3>
<% @node.registrations.each do |reg| %>
<strong>Hub:</strong> <%= reg.hub_id %> role: <%= reg.role %></br>
<% end %>