config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]

      resources :nodes, only: [:index, :update]
    end
  end

  resources :registrations

  resources :nodes

  resources :hubs

  get 'sessions/new'

  resources :users

  resources :payments

  resources :parkings
  get 'enter', to: 'parkings#enter'
  get 'exit', to: 'parkings#exit'

  resources :cars

  resources :lots
  get 'devices', to: 'lots#devices'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root :to => 'nodes#index', :as => 'allnodes'

end

app/models/hub.rb
class Hub < ActiveRecord::Base
  has_many :registrations
  has_many :nodes, :through => :registrations
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  before_action :set_hub, only: [:show, :edit, :update, :destroy]

  # GET /hubs
  # GET /hubs.json
  def index
    @hubs = Hub.all
  end

  # GET /hubs/1
  # GET /hubs/1.json
  def show
  end

  # GET /hubs/new
  def new
    @hub = Hub.new
  end

  # GET /hubs/1/edit
  def edit
  end

  # POST /hubs
  # POST /hubs.json
  def create
    @hub = Hub.new(hub_params)

    respond_to do |format|
      if @hub.save
        format.html { redirect_to @hub, notice: 'Hub was successfully created.' }
        format.json { render :show, status: :created, location: @hub }
      else
        format.html { render :new }
        format.json { render json: @hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hubs/1
  # PATCH/PUT /hubs/1.json
  def update
    respond_to do |format|
      if @hub.update(hub_params)
        format.html { redirect_to @hub, notice: 'Hub was successfully updated.' }
        format.json { render :show, status: :ok, location: @hub }
      else
        format.html { render :edit }
        format.json { render json: @hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hubs/1
  # DELETE /hubs/1.json
  def destroy
    @hub.destroy
    respond_to do |format|
      format.html { redirect_to hubs_url, notice: 'Hub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hub
      @hub = Hub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hub_params
      params.require(:hub).permit(:status, :hardware_id, :max_nodes)
    end
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/views/hubs/_form.html.erb
<%= form_for(@hub) do |f| %>
  <% if @hub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hub.errors.count, "error") %> prohibited this hub from being saved:</h2>

      <ul>
      <% @hub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :hardware_id %><br>
    <%= f.text_field :hardware_id %>
  </div>
  <div class="field">
    <%= f.label :max_nodes %><br>
    <%= f.number_field :max_nodes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hubs/edit.html.erb
<h1>Editing hub</h1>

<%= render 'form' %>

<%= link_to 'Show', @hub %> |
<%= link_to 'Back', hubs_path %>

app/views/hubs/index.html.erb
<h1>Listing hubs</h1>

<% @hubs.each do |hub| %>
<div class="row">
  <div class="col-md-2">
    <%= image_tag("NetworkHub.png") %>
    <h3><%= link_to(hub.hardware_id, hub) %></h3>
    <h5>Status:<%= hub.status %></h5>
    <h5>Max nodes:<%= hub.max_nodes %></h5>
  </div>
  <div class="col-md-10">

    <% i =0 %>
    <table class="table table-striped">
      <tbody>
        <% hub.nodes.each do |node| %>
          <% if i%12 == 0 %>
            <tr>
          <% end %>
            <td>
              <% reg = node.registrations.find_by(hub_id: hub.id) %>
              <% if node.status == 'busy' %>
                <%= button_to("node", node_path(node.id), :class => "btn btn-danger btn-circle", method: :get) %>
              <% elsif node.status == 'idle' %>
              <%= button_to("node", node_path(node.id), :class => "btn btn-success btn-circle", method: :get) %>
              <% else %>
              <%= button_to("node", node_path(node.id), :class => "btn btn-default btn-circle", method: :get) %>
              <% end %>

              <% if reg.role == 'main' %>
              <span class="label label-info"> N<%= node.hardware_id %></span>
              <% else %>
              <span class="label label-default">N<%= node.hardware_id %></span>
              <% end %>

            </td>
          <% if i%12 == 11 or i == hub.nodes.length - 1 %>
            </tr>
          <% end %>

          <% i = i+1 %>
        <% end %>
      </tbody>
    </table>

  </div>
</div>
<hr>
<% end %>


<%= link_to 'New Hub', new_hub_path %>

app/views/hubs/new.html.erb
<h1>New hub</h1>

<%= render 'form' %>

<%= link_to 'Back', hubs_path %>

app/views/hubs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-2">
    <%= image_tag("NetworkHub.png") %>
    <h3><%= link_to(@hub.hardware_id, @hub) %></h3>
    <h5>Status:<%= @hub.status %></h5>
    <h5>Max nodes:<%= @hub.max_nodes %></h5>
    <%= link_to 'Edit', edit_hub_path(@hub) %> |
    <%= link_to 'Back', hubs_path %>
  </div>
  <div class="col-md-10">

    <% i =0 %>
    <table class="table table-striped">
      <tbody>
        <% @hub.nodes.each do |node| %>
          <% if i%16 == 0 %>
            <tr>
          <% end %>
            
            <td>
              <% reg = node.registrations.find_by(hub_id: @hub.id) %>
              <% if reg.role == 'main' %>
              <%= button_to("node", node_path(node.id), :class => "btn btn-success btn-circle", method: :get) %>
              <% else %>
              <%= button_to("node", node_path(node.id), :class => "btn btn-primary btn-circle", method: :get) %>
              <% end %>
              <%= node.hardware_id[4..6] %>
            </td>

          <% if i%16 == 15 or i == @hub.nodes.length - 1 %>
            </tr>
          <% end %>

          <% i = i+1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<a class="btn btn-default" href="#" role="button">Refind visable nodes</a>
<button class="btn btn-default" type="submit">Button</button>