config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]

      resources :nodes, only: [:index, :update]
    end
  end

  resources :registrations

  resources :nodes

  resources :hubs

  get 'sessions/new'

  resources :users

  resources :payments

  resources :parkings
  get 'enter', to: 'parkings#enter'
  get 'exit', to: 'parkings#exit'

  resources :cars

  resources :lots
  get 'devices', to: 'lots#devices'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root :to => 'nodes#index', :as => 'allnodes'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :parking
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        #format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.html { redirect_to '/exit', notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        #format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.html { redirect_to '/exit', notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:unit_price, :total_time, :discount, :total)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.number_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :total_time %><br>
    <%= f.number_field :total_time %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table  class="table table-striped">
  <thead>
    <tr>
      <th>Unit price</th>
      <th>Total time</th>
      <th>Discount</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.unit_price %></td>
        <td><%= payment.total_time %></td>
        <td><%= payment.discount %></td>
        <td><%= payment.total %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Unit price:</strong>
  <%= @payment.unit_price %>
</p>

<p>
  <strong>Total time:</strong>
  <%= @payment.total_time %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @payment.discount %>
</p>

<p>
  <strong>Total:</strong>
  <%= @payment.total %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>